name: Python Workflow
on:
  push:
    paths:
      - 'data/**'  # Trigger the workflow only when changes are made in the 'data' directory

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Replace 'x' with the desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python data/readArabicToHtml.py  # Run the Python script from the 'data' directory
